### ISSUE TITLE
release-it でリリース可能にする

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/create-book#30]
本プロジェクトは release-it を設定しているが、以前 `npm run release` を試したらエラーになった。原因調査と既に同ツールでリリース運用している VFM 設定を参考に本プロジェクトも release-it が通るようにする。

**Comment by akabekobeko** [comment]
エラー内容をメモし忘れているが、これはおそらく Git 管理化で未コミットの変更がある場合に release-it が出すものと思われる。未コミットがない状態で #36 による dry-run を試したら正常に実行された。よって本件は close する。

**Comment by akabekobeko** [comment]
Node.js v12 を下限としたので反映用にリリースを試みたらエラーになった。コミット漏れとは別の問題であった。メッセージを記録しておく。

```
? Commit (chore: release v0.3.2)? Yes
ERROR Error: npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/akabeko/.npm/_logs/2021-10-02T01_47_21_112Z-debug.log
```

ログの関係しそうな箇所

```
26 timing npm:load Completed in 15ms
27 http fetch GET 200 https://registry.npmjs.org/husky-run 671ms (cache miss)
28 timing command:exec Completed in 692ms
29 verbose stack Error: could not determine executable to run
29 verbose stack     at getBinFromManifest (/usr/local/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:15:23)
29 verbose stack     at exec (/usr/local/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:113:15)
30 verbose pkgid husky-run@0.0.0
31 verbose cwd /Users/akabeko/Documents/dev/vivliostyle/create-book
32 verbose Darwin 20.6.0
33 verbose argv "/usr/local/Cellar/node/16.10.0/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "exec" "--yes=false" "--" "husky-run" "pre-commit"
34 verbose node v16.10.0
35 verbose npm  v7.24.0
36 error could not determine executable to run
37 verbose exit 1
```

**Comment by akabekobeko** [comment]
`husky-run` でエラーになっている。npm 更新と共に VFM へあわせて release-it と husky の設定を変更する。

**Comment by akabekobeko** [comment]
npm 更新しただけではダメだった。全く同じエラーとなる。そのうえ `npm publish` は成功してしまうので再試行のためコミットに失敗した `package.json` のバージョンを手動で更新しなければならない。

現時点だと `0.3.3` となっている。この問題が解決するまで

```
? Publish create-book to npm?
```

は `n` とする予定。`npm` としては問題ないため publish 済みのものはそのままに開発環境だけ修正したいので。

**Comment by akabekobeko** [comment]
husky の設定方法が v4 から v6、v7 で変更されたことが原因かもしれない。VFM だと v4 系を利用していた。あちらも npm 更新時に同様の対応が必要。

- [husky を v4 → v7 にアップグレードしたら pre-commit ができなくなった](https://zenn.dev/luvmini511/articles/a47b1aa0310d1a)

**Comment by akabekobeko** [comment]
設定を husky 7 向けに変更してみた。

```
$ npx husky-init
$ npx husky install
$ npm exec -- github:typicode/husky-4-to-7 --remove-v4-config
```

これを実行すると

- npm-scripts の `prepare` に `husky install` が追加される
- package.json の `husky` 設定が削除される
- `husky` 設定に対応するシェル スクリプト ファイルが `.husky/` に出力される

ファイルの内容は以下となっていた。

```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pretty-quick --staged
```

しかしこの状態で `git commit` するとエラーになった。

```
.husky/pre-commit: line 4: pretty-quick: command not found
husky - pre-commit hook exited with code 127 (error)
```

npm としてインストールした `pretty-quick` を見つけられないようだ。では `npm` なら大丈夫か？と npm-scripts に

```json
{
  "scripts": {
    "pretty-quick": "pretty-quick  --staged"
  }
}
```

を定義してシェル スクリプト `.husky/pre-commit` は 

```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run pretty-quick
```

としてみたが、今度は `npm: command not found` となった。パスが通っていないということなのだろうか？継続調査する。

**Comment by akabekobeko** [comment]
以下の issue を読むとシェル スクリプト内でパスを通すことにより対処している例がある。

- [Bug commit from vscode · Issue #912 · typicode/husky](https://github.com/typicode/husky/issues/912)

私の環境は macOS なのでこの方法を採用してもよさそうだ。しかし Windows では問題があるだろう。husky 7 までは Node.js/npm により環境が抽象化されていた。しかしシェル スクリプトに変更されたことで抽象化が自前になってしまった。

とはいえ husky v7 未満へ戻しても npm のバージョンを古いもので固定し続けるリスクがある。他の Vivliostyle プロジェクトはどうしているのかと [vivliostyle-cli/package.json](https://github.com/vivliostyle/vivliostyle-cli/blob/main/package.json) を読んだら v4 を採用していた。

コミット時のコード自動チェックは魅力的であるが、husky v7 の変更は受け入れがたく悩ましい。うまいこと環境抽象化の方法を模索しつつ

- husky v4 or 6 まで戻す
- husky 以外の Git Hooks を検討する
- よい代替がなければ諦める

ことを検討する。

**Comment by akabekobeko** [comment]
このエラーが起きる私の環境を記録しておく。

- macOS Big Sur 11.6
- Node.js v16.10.0
- npm 7.24.0
